version: "3.9"

networks:
  migrator-network:
    driver: bridge

services:
  integration_tests:
    container_name: integration_tests
    build:
      context: ../
      dockerfile: tests/Dockerfile
    command: "true"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=migrator
      - DB_PASSWORD=migrator
      - DB_NAME=migrator
      - DB_SSL=disable
      - TESTDATA_PATH=./testdata
    depends_on:
      db:
        condition: service_healthy
    networks:
      - migrator-network

  db:
    image: postgres:latest
    container_name: migrator-postgres
    restart: always
    environment:
      - POSTGRES_USER=migrator
      - POSTGRES_PASSWORD=migrator
      - POSTGRES_DB=migrator
    ports:
      - '5432:5432'
    healthcheck:
      test: pg_isready -U migrator -d migrator
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - migrator-network
